import ThemeProvider from "@/components/ThemeProvider/ThemeProvider";
import "./globals.css";
// import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import Sidebar from "../components/Sidebar/Sidebar";

const roboto = Roboto({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
});
// const roboto = Roboto({ subsets: ["roboto"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeProvider>
          {/* <div className="container">
            <Sidebar />
            <div className="subContainer">{children}</div>
          </div> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
